# Generated by Django 6.0.3 on 2026-03-27 12:02

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_email", models.EmailField(blank=True, db_index=True, max_length=255)),
                ("name", models.CharField(db_index=True, max_length=32)),
                ("context", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="LabelCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Colleague",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("source", models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10)),
                ("source_id", models.CharField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colleague",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("labels", models.ManyToManyField(blank=True, related_name="colleagues", to="core.label")),
                ("skills", models.ManyToManyField(blank=True, to="core.skill")),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("extra_info", models.TextField(blank=True, max_length=5000)),
                ("source", models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10)),
                ("source_id", models.CharField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_assignments",
                        to="core.colleague",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="label",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="labels", to="core.labelcategory"
            ),
        ),
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Naam")),
                ("label", models.CharField(blank=True, max_length=200)),
                (
                    "abbreviations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lijst van afkortingen, bijv. ["BZK", "MinBZK"]',
                        verbose_name="Afkortingen",
                    ),
                ),
                (
                    "related_ministry_tooi",
                    models.CharField(
                        default="",
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="TOOI identifier moet een URI zijn (https://identifier.overheid.nl/tooi/...)",
                                regex="^https://identifier\\.overheid\\.nl/tooi/",
                            )
                        ],
                    ),
                ),
                (
                    "tooi_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Unieke URI uit organisaties.overheid.nl (bijv. 'https://identifier.overheid.nl/tooi/id/oorg/oorg10264'). Zie: https://standaarden.overheid.nl/tooi/",
                        max_length=200,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="TOOI identifier moet een URI zijn (https://identifier.overheid.nl/tooi/...)",
                                regex="^https://identifier\\.overheid\\.nl/tooi/",
                            )
                        ],
                        verbose_name="TOOI-identifier",
                    ),
                ),
                (
                    "oin_number",
                    models.CharField(
                        blank=True,
                        help_text="Organisatie Identificatienummer - uniek 20-cijferig nummer uit het Logius OIN-register. Wordt gebruikt voor digitale communicatie (PKIoverheid). Niet verplicht. Zie: https://oinregister.logius.nl",
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OIN moet exact 20 cijfers zijn", regex="^\\d{20}$"
                            )
                        ],
                        verbose_name="OIN-nummer",
                    ),
                ),
                (
                    "system_id",
                    models.CharField(
                        default="",
                        help_text="SysteemId - gebruikt op organisatie.overheid.nl voor resources",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        default="",
                        help_text="URL naar de pagina op organisaties.overheid.nl. Als deze is gevuld, komt de organisatie uit een externe bron en zijn de gegevens niet bewerkbaar.",
                        verbose_name="Bronpagina",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop de organisatie is opgeheven.",
                        null=True,
                        verbose_name="Einddatum",
                    ),
                ),
                ("organization_types", models.ManyToManyField(blank=True, to="core.organizationtype")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.organizationunit",
                        verbose_name="Bovenliggende organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie-eenheid",
                "verbose_name_plural": "Organisatie-eenheden",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentOrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("PRIMARY", "Primaire opdrachtgever"), ("INVOLVED", "Betrokken partij")],
                        default="PRIMARY",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_relations",
                        to="core.assignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_relations",
                        to="core.organizationunit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="organizations",
            field=models.ManyToManyField(
                related_name="assignments",
                through="core.AssignmentOrganizationUnit",
                to="core.organizationunit",
                verbose_name="Organisatie-eenheden",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=500)),
                (
                    "period_source",
                    models.CharField(
                        choices=[("ASSIGNMENT", "Neem over van opdracht"), ("SERVICE", "Specifiek voor dienst")],
                        default="ASSIGNMENT",
                        max_length=10,
                    ),
                ),
                ("specific_start_date", models.DateField(blank=True, null=True)),
                ("specific_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("CONCEPT", "Concept"), ("OPEN", "Open"), ("GESLOTEN", "Gesloten")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10)),
                ("source_id", models.CharField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="services", to="core.assignment"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "period_source",
                    models.CharField(
                        choices=[("SERVICE", "Neem over van dienst"), ("PLACEMENT", "Specifiek voor inzet")],
                        default="SERVICE",
                        max_length=10,
                    ),
                ),
                ("specific_start_date", models.DateField(blank=True, null=True)),
                ("specific_end_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10)),
                ("source_id", models.CharField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="placements", to="core.colleague"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="placements", to="core.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "command",
                    models.CharField(db_index=True, help_text="Management command name to execute", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, help_text="Parameters to pass to the command"),
                ),
                ("result", models.JSONField(blank=True, help_text="Result data from the command execution", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_minutes", models.IntegerField(help_text="Task timeout in minutes")),
                ("error_message", models.TextField(blank=True, help_text="Error message if task failed")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("name", "category")},
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(fields=["parent"], name="core_organi_parent__64d754_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(fields=["end_date"], name="core_organi_end_dat_bbd933_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignmentorganizationunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "PRIMARY")), fields=("assignment",), name="unique_primary_per_assignment"
            ),
        ),
    ]
