# Generated by Django 5.2.8 on 2025-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="source",
            field=models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10),
        ),
        migrations.AlterField(
            model_name="colleague",
            name="source",
            field=models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10),
        ),
        migrations.AlterField(
            model_name="placement",
            name="source",
            field=models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="source",
            field=models.CharField(choices=[("otys_iir", "OTYS IIR"), ("wies", "Wies")], max_length=10),
        ),
    ]
