# Generated by Django 6.0.4 on 2026-04-29 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def delete_all_events(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    Event.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_all_events, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Aangemaakt"),
                    ("update", "Gewijzigd"),
                    ("delete", "Verwijderd"),
                    ("deactivate", "Gedeactiveerd"),
                ],
                default="",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="object_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="object_type",
            field=models.CharField(db_index=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(choices=[("user", "Gebruiker"), ("sync", "Sync")], default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["object_type", "object_id"], name="core_event_object__47b576_idx"),
        ),
    ]
