# Generated by Django 5.2.8 on 2025-12-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assignment_source_alter_colleague_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='hours_source',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='specific_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hours_per_week',
        ),
    ]
