# Generated by Django 6.0.6 on 2026-06-08 08:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_split_collapsed_csv_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="context",
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
