# Generated by Django 5.2.9 on 2026-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_label_labelcategory_remove_user_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('context', models.JSONField(default=dict)),
            ],
        ),
    ]
