# Generated by Django 6.0.5 on 2026-06-08 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_event_context"),
        ("core", "0006_alter_placement_period_source_and_more"),
    ]

    operations = []
