# Generated by Django 5.2.9 on 2026-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='extra_info',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
