# Generated by Django 5.2.9 on 2026-01-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_assignment_extra_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelcategory',
            options={'ordering': ['name']},
        ),
    ]
