# Generated by Django 6.0.5 on 2026-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_placement_period_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
    ]
