# Generated by Django 6.0.7 on 2026-07-14 15:18

import logging

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models, transaction

logger = logging.getLogger(__name__)

# Historical LabelCategory name the suborganizations were stored under.
LEGACY_MERK_CATEGORY_NAME = "Merk"


def backfill_suborganization(apps, schema_editor):
    """Backfill Colleague.suborganization from the legacy 'Merk' label category.

    - exactly one merk label  -> set colleague.suborganization to a Suborganization with that name
    - zero merk labels         -> leave suborganization null
    - two or more merk labels  -> leave suborganization null, and log the colleague so an
      admin can contact them (single-value was never enforced under labels).

    The legacy Merk LabelCategory / Label rows and M2M links are intentionally
    left in place for recoverability; a later migration can drop them once the
    backfill is verified in production.
    """
    colleague_model = apps.get_model("core", "Colleague")
    label_category_model = apps.get_model("core", "LabelCategory")
    suborganization_model = apps.get_model("core", "Suborganization")

    category = label_category_model.objects.filter(name=LEGACY_MERK_CATEGORY_NAME).first()
    if category is None:
        # Fresh install without the legacy category — nothing to backfill.
        return

    suborganization_cache = {}

    def get_or_create_suborganization(name):
        if name not in suborganization_cache:
            suborganization_cache[name], _ = suborganization_model.objects.get_or_create(name=name)
        return suborganization_cache[name]

    ambiguous = []  # colleagues with >1 merk label
    backfilled = 0

    for colleague in colleague_model.objects.all():
        merk_labels = list(colleague.labels.filter(category=category))
        if len(merk_labels) == 1:
            with transaction.atomic():
                colleague.suborganization = get_or_create_suborganization(merk_labels[0].name)
                colleague.save(update_fields=["suborganization"])
            backfilled += 1
        elif len(merk_labels) > 1:
            ambiguous.append((colleague.name, colleague.email, [label.name for label in merk_labels]))

    logger.info("Backfilled suborganization for %d colleague(s) from legacy 'Merk' labels.", backfilled)

    if ambiguous:
        logger.warning(
            "%d colleague(s) had multiple 'Merk' labels; suborganization left NULL — contact them to pick one:",
            len(ambiguous),
        )
        for name, email, label_names in ambiguous:
            logger.warning("  - %s <%s>: %s", name, email, ", ".join(label_names))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scrub_legacy_organizations_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suborganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AddField(
            model_name='colleague',
            name='suborganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleagues', to='core.suborganization'),
        ),
        # Schema is in place above; safe to backfill data in the same migration.
        migrations.RunPython(backfill_suborganization, migrations.RunPython.noop),
    ]
