# Generated by Django 6.0.5 on 2026-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_scrub_legacy_organizations_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
    ]
