# Generated by Django 6.0.1 on 2026-01-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_labelcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="source_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="colleague",
            name="source_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="placement",
            name="source_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="source_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
