# Generated by Django 5.2.9 on 2026-01-18 15:37

import django.db.models.functions.text
import wies.core.models
from django.db import migrations, models


def set_display_order_for_existing_categories(apps, schema_editor):
    """Set display_order for existing LabelCategory records."""
    LabelCategory = apps.get_model('core', 'LabelCategory')
    order_mapping = {'Expertise': 10, 'Thema': 20, 'Merk': 30}
    next_order = 100
    for category in LabelCategory.objects.all():
        if category.name in order_mapping:
            category.display_order = order_mapping[category.name]
        else:
            category.display_order = next_order
            next_order += 10
        category.save()


def reverse_migration(apps, schema_editor):
    """No reverse needed - field will be removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_labelcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Lagere waarden verschijnen eerst in filters', verbose_name='Weergavevolgorde'),
        ),
        migrations.RunPython(set_display_order_for_existing_categories, reverse_migration),
        migrations.AlterModelOptions(
            name='labelcategory',
            options={'ordering': ['display_order', django.db.models.functions.text.Lower('name')], 'verbose_name': 'Label categorie', 'verbose_name_plural': 'Label categorieën'},
        ),
        migrations.AlterField(
            model_name='labelcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=wies.core.models.get_next_display_order, help_text='Lagere waarden verschijnen eerst in filters', verbose_name='Weergavevolgorde'),
        ),
    ]
