# Generated by Django 6.0.5 on 2026-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="extra_info",
            field=models.TextField(blank=True),
        ),
    ]
