# Generated by Django 6.0.7 on 2026-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_errorevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="forwarded_for",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="event",
            name="remote_addr",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
