# Generated by Django 6.0.1 on 2026-01-25 16:37

import django.core.validators
import django.db.models.deletion
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def setup_roles(apps, schema_editor):
    """Setup all roles and their permissions."""
    roles = {
        "Beheerder": [
            ("core", "user", ["view_user", "add_user", "delete_user", "change_user"]),
            (
                "core",
                "labelcategory",
                ["view_labelcategory", "add_labelcategory", "change_labelcategory", "delete_labelcategory"],
            ),
            ("core", "label", ["view_label", "add_label", "change_label", "delete_label"]),
            (
                "core",
                "organizationunit",
                ["view_organizationunit", "add_organizationunit", "change_organizationunit", "delete_organizationunit"],
            ),
        ],
        "Consultant": [],
        "Business Development Manager": [
            ("core", "assignment", ["add_assignment"]),
            ("core", "service", ["add_service"]),
            ("core", "placement", ["add_placement"]),
            ("core", "colleague", ["add_colleague"]),
            ("core", "ministry", ["add_ministry"]),
        ],
    }

    for role_name, model_permissions in roles.items():
        group, _created = Group.objects.get_or_create(name=role_name)
        for app_label, model_name, codenames in model_permissions:
            try:
                content_type = ContentType.objects.get(app_label=app_label, model=model_name)
                for codename in codenames:
                    try:
                        perm = Permission.objects.get(codename=codename, content_type=content_type)
                        group.permissions.add(perm)
                    except Permission.DoesNotExist:
                        pass
            except ContentType.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_assignment_source_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Naam")),
                (
                    "abbreviations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lijst van afkortingen, bijv. ["BZK", "MinBZK"]',
                        verbose_name="Afkortingen",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("ministerie", "Ministerie"),
                            ("gemeente", "Gemeente"),
                            ("provincie", "Provincie"),
                            ("waterschap", "Waterschap"),
                            ("directoraat_generaal", "Directoraat-Generaal"),
                            ("directie", "Directie"),
                            ("afdeling", "Afdeling"),
                            ("organisatieonderdeel", "Organisatieonderdeel"),
                            ("zelfstandig_bestuursorgaan", "Zelfstandig Bestuursorgaan"),
                            ("rechtspersoon_wettelijke_taak", "Rechtspersoon met Wettelijke Taak"),
                            ("stichting", "Stichting"),
                            ("staatsdeelneming", "Staatsdeelneming"),
                            ("hoog_college_van_staat", "Hoog College van Staat"),
                            ("rechtspraak", "Rechtspraak"),
                            ("politie", "Politie"),
                            ("kabinet_van_de_koning", "Kabinet van de Koning"),
                            ("publiekrechtelijke_instelling", "Publiekrechtelijke Instelling"),
                            ("speciaal_sectorbedrijf", "Speciaal Sectorbedrijf"),
                            ("gemeenschappelijke_regeling", "Gemeenschappelijke Regeling"),
                            ("caribisch_openbaar_lichaam", "Caribisch Openbaar Lichaam"),
                            ("agentschap", "Agentschap"),
                            ("shared_service_organisatie", "Shared Service Organisatie"),
                            ("planbureau", "Planbureau"),
                            ("adviescollege", "Adviescollege"),
                            ("inspectie", "Inspectie"),
                        ],
                        max_length=30,
                        verbose_name="Type organisatie",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actief")),
                (
                    "tooi_identifier",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Unieke URI uit organisaties.overheid.nl "
                            "(bijv. 'https://identifier.overheid.nl/tooi/id/oorg/oorg10264'). "
                            "Zie: https://standaarden.overheid.nl/tooi/"
                        ),
                        max_length=200,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="TOOI identifier moet een URI zijn (https://identifier.overheid.nl/tooi/...)",
                                regex="^https://identifier\\.overheid\\.nl/tooi/",
                            )
                        ],
                        verbose_name="TOOI-identifier",
                    ),
                ),
                (
                    "oin_number",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Organisatie Identificatienummer - uniek 20-cijferig nummer uit het Logius OIN-register. "
                            "Wordt gebruikt voor digitale communicatie (PKIoverheid). Niet verplicht. "
                            "Zie: https://oinregister.logius.nl"
                        ),
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OIN moet exact 20 cijfers zijn",
                                regex="^\\d{20}$",
                            )
                        ],
                        verbose_name="OIN-nummer",
                    ),
                ),
                (
                    "previous_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"name": "Digitale Overheid", "until": "2024-01-01"}]',
                        verbose_name="Vorige namen",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.organizationunit",
                        verbose_name="Bovenliggende organisatie",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organisatie die deze heeft overgenomen (bij fusie/opheffing)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessors",
                        to="core.organizationunit",
                        verbose_name="Opvolger",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Verwijderd op",
                        help_text="Tijdstip van soft delete. Null = niet verwijderd.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie-eenheid",
                "verbose_name_plural": "Organisatie-eenheden",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentOrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primaire organisatie"),
                            ("INVOLVED", "Betrokken partij"),
                            ("SUCCESSOR", "Opvolger (na overdracht)"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True, verbose_name="Geldig vanaf")),
                ("effective_until", models.DateField(blank=True, null=True, verbose_name="Geldig tot")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_relations",
                        to="core.assignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_relations",
                        to="core.organizationunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opdracht-organisatie koppeling",
                "verbose_name_plural": "Opdracht-organisatie koppelingen",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="organizations",
            field=models.ManyToManyField(
                related_name="assignments",
                through="core.AssignmentOrganizationUnit",
                to="core.organizationunit",
                verbose_name="Organisatie-eenheden",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(fields=["parent", "is_active"], name="core_organi_parent__a926e0_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignmentorganizationunit",
            constraint=models.UniqueConstraint(
                fields=("assignment", "organization", "role"),
                name="unique_assignment_org_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentorganizationunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "PRIMARY")),
                fields=("assignment",),
                name="unique_primary_org_per_assignment",
            ),
        ),
        migrations.RunPython(setup_roles, migrations.RunPython.noop),
    ]
