# Generated by Django 6.0.2 on 2026-02-06 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_assignment_source_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="ministry",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="organization",
        ),
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Naam")),
                (
                    "abbreviations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lijst van afkortingen, bijv. ["BZK", "MinBZK"]',
                        verbose_name="Afkortingen",
                    ),
                ),
                (
                    "tooi_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Unieke URI uit organisaties.overheid.nl "
                        "(bijv. 'https://identifier.overheid.nl/tooi/id/oorg/oorg10264'). "
                        "Zie: https://standaarden.overheid.nl/tooi/",
                        max_length=200,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="TOOI identifier moet een URI zijn (https://identifier.overheid.nl/tooi/...)",
                                regex="^https://identifier\\.overheid\\.nl/tooi/",
                            )
                        ],
                        verbose_name="TOOI-identifier",
                    ),
                ),
                (
                    "oin_number",
                    models.CharField(
                        blank=True,
                        help_text="Organisatie Identificatienummer - uniek 20-cijferig nummer "
                        "uit het Logius OIN-register. Wordt gebruikt voor digitale communicatie (PKIoverheid). "
                        "Niet verplicht. Zie: https://oinregister.logius.nl",
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OIN moet exact 20 cijfers zijn", regex="^\\d{20}$"
                            )
                        ],
                        verbose_name="OIN-nummer",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL naar de pagina op organisaties.overheid.nl. "
                        "Als deze is gevuld, komt de organisatie uit een externe bron "
                        "en zijn de gegevens niet bewerkbaar.",
                        verbose_name="Bronpagina",
                    ),
                ),
                ("organization_types", models.ManyToManyField(blank=True, to="core.organizationtype")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.organizationunit",
                        verbose_name="Bovenliggende organisatie",
                    ),
                ),
                (
                    "related_ministry",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="core.organizationunit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie-eenheid",
                "verbose_name_plural": "Organisatie-eenheden",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentOrganizationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_relations",
                        to="core.assignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_relations",
                        to="core.organizationunit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="organizations",
            field=models.ManyToManyField(
                related_name="assignments",
                through="core.AssignmentOrganizationUnit",
                to="core.organizationunit",
                verbose_name="Organisatie-eenheden",
            ),
        ),
        migrations.DeleteModel(
            name="Ministry",
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(fields=["parent"], name="core_organi_parent__64d754_idx"),
        ),
    ]
