# Generated by Django 6.0.7 on 2026-07-29 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_event_ip_event_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="assignment_hours_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)],
                verbose_name="Uren per week op plaatsing",
            ),
        ),
        migrations.CreateModel(
            name="ContractPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="Uren per week",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Einddatum")),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_periods",
                        to="core.colleague",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
