# Generated by Django 6.0.7 on 2026-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_event_ip_event_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("LEAD", "Lead"), ("OPEN", "Open"), ("INGEVULD", "Ingevuld"), ("GESLOTEN", "Gesloten")],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
