# Generated by Django 6.0.1 on 2026-01-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_organizationunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationunit",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "URL naar de pagina op organisaties.overheid.nl. Als deze is gevuld, "
                    "komt de organisatie uit een externe bron en zijn de gegevens niet bewerkbaar."
                ),
                verbose_name="Bronpagina",
            ),
        ),
    ]
