# Generated by Django 6.0.7 on 2026-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_event_ip_event_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleague",
            name="theme",
            field=models.CharField(
                choices=[("system", "Systeem"), ("light", "Licht"), ("dark", "Donker")], default="system", max_length=6
            ),
        ),
    ]
