# Generated by Django 6.0.3 on 2026-03-09 13:53

from django.db import migrations, models
from django.db.models import Count


def deduplicate_primary_roles(apps, schema_editor):
    # make sure there is only a single primary client
    AssignmentOrganizationUnit = apps.get_model("core", "AssignmentOrganizationUnit")
    duplicates = (
        AssignmentOrganizationUnit.objects.filter(role="PRIMARY")
        .values("assignment_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        pks = list(
            AssignmentOrganizationUnit.objects.filter(assignment_id=dup["assignment_id"], role="PRIMARY")
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        # Keep the first as PRIMARY, set the rest to INVOLVED
        AssignmentOrganizationUnit.objects.filter(pk__in=pks[1:]).update(role="INVOLVED")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentorganizationunit",
            name="role",
            field=models.CharField(
                choices=[("PRIMARY", "Primaire opdrachtgever"), ("INVOLVED", "Betrokken partij")],
                default="PRIMARY",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.RunPython(
            deduplicate_primary_roles,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="assignmentorganizationunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "PRIMARY")), fields=("assignment",), name="unique_primary_per_assignment"
            ),
        ),
    ]
