# Generated by Django 6.0.7 on 2026-08-05 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_colleague_theme"),
        ("core", "0011_suborganization_colleague_suborganization"),
    ]

    operations = []
