# Generated by Django 6.0.7 on 2026-08-05

import django.core.validators
from django.db import migrations, models


def copy_hours_to_service(apps, schema_editor):
    """Copy each Placement's hours onto its Service.

    Ordered by id so that, when a Service has more than one Placement, the
    last (highest-id) placement wins deterministically.
    """
    Placement = apps.get_model("core", "Placement")
    for placement in Placement.objects.exclude(assignment_hours_per_week=None).order_by("id"):
        service = placement.service
        service.assignment_hours_per_week = placement.assignment_hours_per_week
        service.save(update_fields=["assignment_hours_per_week"])


def copy_hours_to_placements(apps, schema_editor):
    """Reverse: copy each Service's hours back onto all of its Placements."""
    Service = apps.get_model("core", "Service")
    for service in Service.objects.exclude(assignment_hours_per_week=None):
        service.placements.update(assignment_hours_per_week=service.assignment_hours_per_week)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_placement_assignment_hours_per_week_contractperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="assignment_hours_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(40),
                ],
                verbose_name="Uren per week",
            ),
        ),
        migrations.RunPython(copy_hours_to_service, copy_hours_to_placements),
    ]
