# Generated by Django 6.0.3 on 2026-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(choices=[("OPEN", "OPEN"), ("INGEVULD", "INGEVULD")], default="LEAD", max_length=20),
        ),
    ]
