# Generated by Django 6.0.3 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentorganizationunit",
            name="role",
            field=models.CharField(
                choices=[("PRIMARY", "Primaire opdrachtgever"), ("INVOLVED", "Betrokken partij")],
                default="PRIMARY",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentorganizationunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "PRIMARY")), fields=("assignment",), name="unique_primary_per_assignment"
            ),
        ),
    ]
