# Generated by Django 6.0.7 on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_service_assignment_hours_per_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placement",
            name="assignment_hours_per_week",
        ),
    ]
