# Generated by Django 6.0.8 on 2026-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_colleague_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("LEAD", "Lead"), ("OPEN", "Open"), ("INGEVULD", "Ingevuld"), ("GESLOTEN", "Gesloten")],
                db_index=True,
                default="OPEN",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
