# Generated by Django 6.0.3 on 2026-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_assignment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[("CONCEPT", "Concept"), ("OPEN", "Open"), ("GESLOTEN", "Gesloten")],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
