# Generated by Django 6.0.8 on 2026-09-10 09:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_colleague_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)],
                verbose_name="Uren per week",
            ),
        ),
        migrations.CreateModel(
            name="ContractPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="Uren per week",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Einddatum")),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_periods",
                        to="core.colleague",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractperiode",
                "verbose_name_plural": "Contractperioden",
                "ordering": ["-start_date"],
            },
        ),
    ]
