# Generated by Django 6.0.8 on 2026-09-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_contractperiod_service_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationunit",
            name="main_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.organizationtype",
            ),
        ),
    ]
