# Generated by Django 6.0.8 on 2026-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_contractperiod_service_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
