# Generated by Django 6.0.8 on 2026-09-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='closing_reason',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Reden van sluiten'),
        ),
    ]
