# Generated by Django 6.0.8 on 2026-09-28 16:13
#
# Converts OrganizationUnit.organization_types from a plain M2M to an ordered
# through model (OrganizationUnitType) WITHOUT losing the existing links.
#
# Django's autodetected migration would CreateModel a fresh table and, via the
# AlterField, drop the auto-created join table `core_organizationunit_organization_types`
# — throwing away every existing unit↔type link. Instead we:
#   1. rename that join table to the through model's table and add the columns
#      the through model needs (state + real SQL kept in sync via
#      SeparateDatabaseAndState), then
#   2. backfill `position` deterministically for existing rows.
#
# Existing rows lose the source ordering (a plain M2M never stored it), so the
# backfill is arbitrary-but-stable. A later `sync_organizations` /
# `load_full_data --profile full` run rewrites positions from the real source
# order (see wies/core/services/organizations.py).

import django.db.models.deletion
from django.db import migrations, models


def backfill_positions(apps, schema_editor):
    """Give existing rows a deterministic position per unit (ordered by type id)."""
    OrganizationUnitType = apps.get_model("core", "OrganizationUnitType")
    by_unit: dict[int, list] = {}
    for link in OrganizationUnitType.objects.all().order_by("organization_unit_id", "organization_type_id"):
        by_unit.setdefault(link.organization_unit_id, []).append(link)
    for links in by_unit.values():
        for position, link in enumerate(links):
            if link.position != position:
                link.position = position
                link.save(update_fields=["position"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_contractperiod_service_hours"),
    ]

    operations = [
        # --- Introduce the through model in Django's state only; the database
        # keeps the existing auto-created join table, which we rename + extend
        # below so no link rows are lost. ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="OrganizationUnitType",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("position", models.PositiveSmallIntegerField(default=0)),
                        (
                            "organization_type",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organizationtype"),
                        ),
                        (
                            "organization_unit",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organizationunit"),
                        ),
                    ],
                    options={
                        "ordering": ["position"],
                    },
                ),
                migrations.AlterField(
                    model_name="organizationunit",
                    name="organization_types",
                    field=models.ManyToManyField(
                        blank=True, through="core.OrganizationUnitType", to="core.organizationtype"
                    ),
                ),
            ],
            database_operations=[
                # Rename the auto-created join table to the through model's table.
                migrations.RunSQL(
                    sql="ALTER TABLE core_organizationunit_organization_types RENAME TO core_organizationunittype;",
                    reverse_sql="ALTER TABLE core_organizationunittype RENAME TO core_organizationunit_organization_types;",
                ),
                # Rename the FK columns to match the through model's field names.
                migrations.RunSQL(
                    sql="ALTER TABLE core_organizationunittype RENAME COLUMN organizationunit_id TO organization_unit_id;",
                    reverse_sql="ALTER TABLE core_organizationunittype RENAME COLUMN organization_unit_id TO organizationunit_id;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE core_organizationunittype RENAME COLUMN organizationtype_id TO organization_type_id;",
                    reverse_sql="ALTER TABLE core_organizationunittype RENAME COLUMN organization_type_id TO organizationtype_id;",
                ),
                # Add the new position column.
                migrations.RunSQL(
                    sql="ALTER TABLE core_organizationunittype ADD COLUMN position smallint NOT NULL DEFAULT 0;",
                    reverse_sql="ALTER TABLE core_organizationunittype DROP COLUMN position;",
                ),
                # Drop the M2M's auto-created unique constraint; AddConstraint
                # below recreates an equivalent one under a state-tracked name.
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE core_organizationunittype "
                        "DROP CONSTRAINT core_organizationunit_or_organizationunit_id_orga_40407705_uniq;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE core_organizationunittype "
                        "ADD CONSTRAINT core_organizationunit_or_organizationunit_id_orga_40407705_uniq "
                        "UNIQUE (organization_unit_id, organization_type_id);"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="organizationunittype",
            constraint=models.UniqueConstraint(
                fields=("organization_unit", "organization_type"), name="uniq_unit_type"
            ),
        ),
        migrations.RunPython(backfill_positions, migrations.RunPython.noop),
    ]
