# Generated by Django 6.0.8 on 2026-09-30 15:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_main_type(apps, schema_editor):
    """Give every typed unit a main_type until the next org sync sets the real one.

    The source order of the types (the first-listed is the main type) was never
    stored, so pick the type with the lowest pk, which is what
    ``organization_types.first()`` returns. Correct for single-type units; the
    next sync fixes a multi-type unit whose main type is another one.
    """
    OrganizationUnit = apps.get_model("core", "OrganizationUnit")
    through = OrganizationUnit.organization_types.through

    first_type_by_unit: dict[int, int] = {}
    links = through.objects.order_by("organizationunit_id", "organizationtype_id")
    for unit_id, type_id in links.values_list("organizationunit_id", "organizationtype_id"):
        first_type_by_unit.setdefault(unit_id, type_id)

    units = list(OrganizationUnit.objects.filter(id__in=first_type_by_unit))
    for unit in units:
        unit.main_type_id = first_type_by_unit[unit.id]
    OrganizationUnit.objects.bulk_update(units, ["main_type"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_contractperiod_service_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationunit",
            name="main_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.organizationtype",
            ),
        ),
        migrations.RunPython(backfill_main_type, migrations.RunPython.noop),
    ]
