# Generated by Django 6.0.3 on 2026-03-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_copy_user_labels_to_colleague"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleague",
            name="profile_picture",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="colleague",
            name="profile_picture_content_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="colleague",
            name="profile_picture_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
