# Generated by Django 6.0.8 on 2026-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_organizationunit_main_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
