# Generated by Django 6.0.3 on 2026-03-30 15:06

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def deduplicate_colleagues(apps, schema_editor):
    """Remove duplicate Colleague rows (same email + source), keeping the oldest.

    Relations (placements, owned_assignments, skills, labels) are reassigned
    from duplicates to the kept record before deletion.
    """
    Colleague = apps.get_model("core", "Colleague")
    Placement = apps.get_model("core", "Placement")
    Assignment = apps.get_model("core", "Assignment")

    duplicates = Colleague.objects.values("email", "source").annotate(count=models.Count("id")).filter(count__gt=1)

    if duplicates.exists():
        logger.info("Found %d duplicate (email, source) groups in Colleague", duplicates.count())

    for dup in duplicates:
        colleagues = Colleague.objects.filter(email=dup["email"], source=dup["source"]).order_by("id")
        keep = colleagues.first()
        to_delete = colleagues.exclude(id=keep.id)

        logger.info(
            "Deduplicating email=%s source=%s: keeping id=%d, removing ids=%s",
            dup["email"],
            dup["source"],
            keep.id,
            [c.id for c in to_delete],
        )

        for old in to_delete:
            # Reassign placements
            Placement.objects.filter(colleague=old).update(colleague=keep)
            # Reassign owned assignments
            Assignment.objects.filter(owner=old).update(owner=keep)
            # Merge skills
            for skill in old.skills.all():
                keep.skills.add(skill)
            # Merge labels
            for label in old.labels.all():
                keep.labels.add(label)
            # Prefer linked user if keep doesn't have one
            if old.user and not keep.user:
                keep.user = old.user
                keep.save(update_fields=["user"])

            old.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_copy_user_labels_to_colleague"),
    ]

    operations = [
        migrations.RunPython(deduplicate_colleagues, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="colleague",
            constraint=models.UniqueConstraint(fields=("email", "source"), name="unique_colleague_email_source"),
        ),
    ]
