# Generated by Django 6.0.8 on 2026-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_service_description_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(
                choices=[("user", "Gebruiker"), ("sync", "Sync"), ("system", "Systeem")], max_length=16
            ),
        ),
    ]
