# Generated by Django 6.1.2 on 2026-10-08 10:12

from django.db import migrations, models
from django.db.models import F


def copy_open_role_text(apps, schema_editor):
    """Gives each existing aanvraag its role text as a starting description.

    Copied, not moved: "Taken" stays as it was, so filling the aanvraag later
    still finds it, and the reverse step has nothing to restore.
    """
    Service = apps.get_model("core", "Service")
    Service.objects.filter(placements__isnull=True).exclude(description="").update(request_description=F("description"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_service_description_optional"),
    ]

    operations = [
        # Room for a vacancy text taken over as taken when the aanvraag is filled.
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="service",
            name="duration_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (3, "3 maanden"),
                    (6, "6 maanden"),
                    (9, "9 maanden"),
                    (12, "1 jaar"),
                    (18, "18 maanden"),
                    (24, "2 jaar"),
                ],
                null=True,
                verbose_name="Duur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="Standplaats"),
        ),
        migrations.AddField(
            model_name="service",
            name="request_description",
            field=models.TextField(blank=True, max_length=10000, verbose_name="Aanvraagomschrijving"),
        ),
        migrations.AddField(
            model_name="service",
            name="starts_immediately",
            field=models.BooleanField(default=False, verbose_name="Per direct"),
        ),
        migrations.RunPython(copy_open_role_text, migrations.RunPython.noop),
    ]
