# Generated by Django 6.0.8 on 2026-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_service_description_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Human-readable task name, snapshotted at creation (falls back to command when empty)",
                max_length=100,
            ),
        ),
    ]
