services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app:z
    command: python manage.py runserver 0.0.0.0:8080
    env_file: .env
  db_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app:z
    command: python manage.py db_worker
    env_file: .env
