# Generated by Django 5.2.7 on 2025-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExactEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_medewerker', models.CharField(max_length=200, verbose_name='Naam medewerker')),
                ('aantal_uren', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Aantal uren')),
                ('rin_nummer', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RIN nummer')),
                ('schaalniveau', models.CharField(blank=True, max_length=10, null=True, verbose_name='Schaalniveau')),
                ('kostenplaats', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kostenplaats')),
                ('if_kf', models.CharField(blank=True, choices=[('IF', 'IF'), ('KF', 'KF')], max_length=2, null=True, verbose_name='IF/KF')),
                ('uren_schrijven', models.BooleanField(default=True, verbose_name='Uren schrijven - nodig voor RC')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail - gebruikt door RC')),
                ('organisatieonderdeel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organisatieonderdeel - gebruikt door RC')),
                ('manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manager - gebruikt door RC')),
                ('status', models.CharField(choices=[('ACTIEF', 'Actief'), ('INACTIEF', 'Inactief'), ('VERLOF', 'Verlof'), ('UITDIENST', 'Uit dienst')], default='ACTIEF', max_length=20, verbose_name='Status - gebruikt door RC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exact Employee',
                'verbose_name_plural': 'Exact Employees',
                'ordering': ['naam_medewerker'],
            },
        ),
        migrations.CreateModel(
            name='ExactProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnaam', models.CharField(max_length=200, verbose_name='Projectnaam')),
                ('odi_thema', models.CharField(max_length=100, verbose_name='ODI thema')),
                ('product_dienst_assortiment', models.CharField(max_length=150, verbose_name='Product/dienst assortiment')),
                ('start_datum', models.DateField(verbose_name='Start datum')),
                ('eind_datum', models.DateField(verbose_name='Eind datum')),
                ('aantal_uur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aantal uur')),
                ('tarief', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarief')),
                ('type_project', models.CharField(choices=[('INTERN', 'Intern'), ('EXTERN', 'Extern'), ('OVERHEID', 'Overheid')], max_length=20, verbose_name='Type - gebruikt door RC')),
                ('organisatieonderdeel', models.CharField(max_length=100, verbose_name='Organisatieonderdeel - gebruikt door RC')),
                ('manager', models.CharField(max_length=200, verbose_name='Manager - gebruikt door RC')),
                ('moeder', models.CharField(blank=True, max_length=200, verbose_name='Moeder - gebruikt door RC')),
                ('contract_besteld_door', models.CharField(max_length=200, verbose_name='Contract: Besteld door')),
                ('contract_contactpersoon', models.CharField(max_length=200, verbose_name='Contract: contactpersoon opdrachtgever')),
                ('contract_factuur_voor', models.CharField(max_length=200, verbose_name='Contract: Factuur voor')),
                ('contract_ter_attentie_van', models.CharField(max_length=200, verbose_name='Contract: Ter attentie van')),
                ('contract_eenzijdig_getekend', models.BooleanField(default=False, verbose_name='Contract: 1-zijdig getekend')),
                ('contract_tweezijdig_getekend', models.BooleanField(default=False, verbose_name='Contract: 2-zijdig getekend')),
                ('uw_referentie', models.CharField(max_length=100, verbose_name='Uw referentie - nodig voor contractafhandeling')),
                ('uw_kenmerk', models.CharField(max_length=100, verbose_name='Uw kenmerk - nodig voor contractafhandeling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exact Project',
                'verbose_name_plural': 'Exact Projects',
                'ordering': ['projectnaam'],
            },
        ),
    ]
