# Generated by Django 6.0.6 on 2026-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rijksauth", "0004_remove_super_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
