# Generated by Django 6.0.7 on 2026-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rijksauth", "0005_user_onboarding_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="authevent",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authevent",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
