# Generated by Django 6.0.7 on 2026-07-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rijksauth", "0005_user_onboarding_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
