# Generated by Django 5.2.4 on 2025-07-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_colleague'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.colleague')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='colleagues',
            field=models.ManyToManyField(related_name='projects', through='projects.Assignment', to='projects.colleague'),
        ),
    ]
