# Generated by Django 5.2.4 on 2025-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_assignment_project_colleagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('LEAD', 'LEAD'), ('OPEN', 'OPEN'), ('LOPEND', 'LOPEND'), ('AFGEWEZEN', 'AFGEWEZEN'), ('HISTORISCH', 'HISTORISCH')], default='LEAD', max_length=20),
        ),
    ]
