# Generated by Django 5.2.4 on 2025-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(default=''),
        ),
    ]
