# Generated by Django 5.2.4 on 2025-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_end_date_project_extra_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colleagues',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.Assignment', to='projects.colleague'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
