# Generated by Django 5.2.4 on 2025-07-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_desired_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desired_skills',
            new_name='skills',
        ),
    ]
