# Generated by Django 5.2.4 on 2025-07-10 14:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_desired_skills_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleague',
            name='function',
        ),
        migrations.AddField(
            model_name='colleague',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BE_DEV', 'Backend development'), ('FE_DEV', 'Frontend development'), ('PO', 'Product owner'), ('UX_DES', 'UX designer'), ('AI_CONS', 'AI Consultant'), ('AI_JUR', 'AI Jurist'), ('RES', 'Researcher'), ('DAT_ENG', 'Data engineer'), ('PROJ_LEAD', 'Project leader')], max_length=60),
        ),
    ]
