# Generated by Django 5.2.4 on 2025-07-15 15:48

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0011_remove_project_colleagues_remove_project_skills_and_more'), ('projects', '0012_alter_assignment_colleague'), ('projects', '0013_alter_assignment_hours_per_week'), ('projects', '0014_project_project_type'), ('projects', '0015_rename_project_projectbase_job_project'), ('projects', '0016_alter_assignment_colleague')]

    dependencies = [
        ('projects', '0010_remove_colleague_function_colleague_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='colleagues',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BE_DEV', 'Backend development'), ('FE_DEV', 'Frontend development'), ('PO', 'Product owner'), ('UX_DES', 'UX designer'), ('AI_CONS', 'AI Consultant'), ('AI_JUR', 'AI Jurist'), ('RES', 'Researcher'), ('DAT_ENG', 'Data engineer'), ('PROJ_LEAD', 'Project leader')], max_length=60),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hours_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL')], default='GROUP', max_length=20),
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectBase',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.projectbase',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.projectbase',),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='colleague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.colleague'),
        ),
    ]
