"""
Django settings for wies project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy

# env vars

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "wies"

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "wies.rijksauth",
    "wies.core",
    "wies.kb",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "wies.core.middleware.ResponseHeadersMiddleware",
    # WhiteNoise is added in production.py only — see prod settings.
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "config.jinja2.environment",
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wies.core.context_processors.onboarding",
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "wies"),
        "USER": os.environ.get("POSTGRES_USER", "wies"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "wies"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "nl-nl"
LANGUAGES = [
    ("nl", gettext_lazy("Nederlands")),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours (workday)

LOGIN_URL = "login"

AUTHENTICATION_BACKENDS = [
    "wies.rijksauth.auth_backend.AuthBackend",
]

AUTH_USER_MODEL = "rijksauth.User"

# User.email uniqueness is enforced by a case-insensitive UniqueConstraint
# (Lower("email")), not by field-level unique=True, so Django's W004 doesn't
# apply.
SILENCED_SYSTEM_CHECKS = ["auth.W004"]

AUTH_NO_ACCESS_URL = "/geen-toegang/"

OIDC_ID_TOKEN_SESSION_KEY = "oidc_id_token"  # noqa: S105 (hardcoded-password) — session key name, not a secret
OIDC_POST_LOGOUT_COOKIE_NAME = "wies_post_logout"

# Allowed email domains for ODI users
ALLOWED_EMAIL_DOMAINS = ["@rijksoverheid.nl", "@minbzk.nl"]

# Comma-separated emails that can access the staff dashboard / database pages.
STAFF_EMAILS = [email.strip().lower() for email in os.environ.get("STAFF_EMAILS", "").split(",") if email.strip()]

# Toggle for destructive staff database actions (clear data, load dummy data).
# Default off (production-safe). Set to "true" in local/staging environments.
ENABLE_DESTRUCTIVE_STAFF_ACTIONS = os.environ.get("ENABLE_DESTRUCTIVE_STAFF_ACTIONS", "").lower() == "true"

# Number of trusted reverse-proxy hops in front of the app. Used to pick the
# right X-Forwarded-For entry when logging the client IP on audit/auth events.
# 0 = trust nothing, use REMOTE_ADDR only (safe default for dev/test — no
# header spoofing honoured). Production overrides this (see production.py).
TRUSTED_PROXY_HOPS = int(os.environ.get("TRUSTED_PROXY_HOPS", "0"))

# OTYS API settings
OTYS_API_KEY = os.environ.get("OTYS_API_KEY", "")
OTYS_URL = os.environ.get("OTYS_URL", "")

# MATTERMOST settings
MATTERMOST_TOKEN = os.environ.get("MATTERMOST_TOKEN", "")
MATTERMOST_WIES_OPS_CHANNEL_URL = os.environ.get("MATTERMOST_WIES_OPS_CHANNEL_URL", "")

# SITE_BASE_URL is used if links need to be shared outside (e.g. in mattermost message)
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "").rstrip("/")

# Error monitoring throttle: within this window, only the first error per
# (exception_type, path) is persisted + posted to Mattermost
ERROR_THROTTLE_MINUTES = 5

# Knowledge base (ODI start portal) — see wies/kb/.
# The built Hugo site lives in a MinIO bucket; the KB serves it auth-gated and
# the db_worker publish job pulls a GitHub release artifact into a new prefix.
# Read from env with dev-friendly defaults here; production.py and worker.py
# re-require the ones each process actually needs (fail-fast on missing secrets).
# ZAD (the deploy platform) injects OBJECT_STORE_* directly for a provisioned MinIO
# service, so read those verbatim — no deploy-side remap. boto3 needs a single
# endpoint URL, so compose it from host+port; ZAD gives no scheme, default http
# (intra-cluster), override OBJECT_STORE_SCHEME when the endpoint is TLS.
_obj_host = os.environ.get("OBJECT_STORE_HOST", "")
_obj_port = os.environ.get("OBJECT_STORE_PORT", "")
_obj_scheme = os.environ.get("OBJECT_STORE_SCHEME", "http")
OBJECT_STORE_ENDPOINT = f"{_obj_scheme}://{_obj_host}:{_obj_port}" if _obj_host and _obj_port else ""
OBJECT_STORE_USER = os.environ.get("OBJECT_STORE_USER", "")
OBJECT_STORE_PASSWORD = os.environ.get("OBJECT_STORE_PASSWORD", "")
OBJECT_STORE_BUCKET_NAME = os.environ.get("OBJECT_STORE_BUCKET_NAME", "")
# Region is cosmetic for MinIO but boto3 requires one.
OBJECT_STORE_REGION = os.environ.get("OBJECT_STORE_REGION", "us-east-1")
# Object key holding the name of the currently-active site prefix (atomic publish).
KB_CURRENT_POINTER_KEY = os.environ.get("KB_CURRENT_POINTER_KEY", "sites/CURRENT")

# Private content repo (owner/name) whose latest GitHub release artifact holds
# the built site, and a read token to download it. Only the worker needs these.
KB_CONTENT_GITHUB_REPO = os.environ.get("KB_CONTENT_GITHUB_REPO", "DigiGilde/odi-startpagina")
KB_CONTENT_GITHUB_TOKEN = os.environ.get("KB_CONTENT_GITHUB_TOKEN", "")
