"""
Django settings for wies project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import jinja_roos_components
from django.utils.translation import gettext_lazy

# env vars

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "wies"

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "wies.rijksauth",
    "wies.core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "wies.core.middleware.SecurityHeadersMiddleware",
    # WhiteNoise is added in production.py only — see prod settings.
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "config.jinja2.environment",
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wies.core.context_processors.rijksprofielservice",
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "wies"),
        "USER": os.environ.get("POSTGRES_USER", "wies"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "wies"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "nl-nl"
LANGUAGES = [
    ("nl", gettext_lazy("Nederlands")),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    Path(jinja_roos_components.__file__).parent / "static",  # dir 'roos'
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours (workday)
SESSION_COOKIE_NAME = "wies_sessionid"  # avoid clashing with other Django apps on localhost
CSRF_COOKIE_NAME = "wies_csrftoken"

LOGIN_URL = "login"

AUTHENTICATION_BACKENDS = [
    "wies.rijksauth.auth_backend.AuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "rijksauth.User"

# User.email uniqueness is enforced by a case-insensitive UniqueConstraint
# (Lower("email")), not by field-level unique=True, so Django's W004 doesn't
# apply.
SILENCED_SYSTEM_CHECKS = ["auth.W004"]

AUTH_NO_ACCESS_URL = "/geen-toegang/"

OIDC_ID_TOKEN_SESSION_KEY = "oidc_id_token"  # noqa: S105 (hardcoded-password) — session key name, not a secret
OIDC_POST_LOGOUT_COOKIE_NAME = "wies_post_logout"

# Allowed email domains for ODI users
ALLOWED_EMAIL_DOMAINS = ["@rijksoverheid.nl", "@minbzk.nl"]

# Comma-separated emails that can access the staff dashboard / database pages.
STAFF_EMAILS = [email.strip().lower() for email in os.environ.get("STAFF_EMAILS", "").split(",") if email.strip()]

# Toggle for destructive staff database actions (clear data, load dummy data).
# Default off (production-safe). Set to "true" in local/staging environments.
ENABLE_DESTRUCTIVE_STAFF_ACTIONS = os.environ.get("ENABLE_DESTRUCTIVE_STAFF_ACTIONS", "").lower() == "true"

# OTYS API settings
OTYS_API_KEY = os.environ.get("OTYS_API_KEY", "")
OTYS_URL = os.environ.get("OTYS_URL", "")

# Rijksprofielservice (PoC) settings.
# Sinds PoC2 is de profielservice zelf de OAuth Authorization Server
# (django-oauth-toolkit). Twee clients zijn per app geregistreerd:
# - `RIJKSPROFIELSERVICE_CLIENT_ID` (auth-code + PKCE) — voor de consent-flow
#   waarmee Wies de SSO-subject van de gebruiker vaststelt.
# - `RIJKSPROFIELSERVICE_M2M_CLIENT_ID` (client-credentials) — voor de batch-API
#   waarmee Wies (collega-)profielen ophaalt.
#
# Twee URLs omdat Wies in twee richtingen praat:
# - BROWSER_URL: waar Django de browser van de gebruiker naartoe stuurt (moet bereikbaar
#   zijn vanaf de machine van de gebruiker, bv. localhost:8000).
# - API_URL / TOKEN_URL: waar Wies' server back-channel HTTP-calls doet (moet vanuit
#   de Django-container bereikbaar zijn; op macOS werkt host.docker.internal).
RIJKSPROFIELSERVICE_BROWSER_URL = os.environ.get("RIJKSPROFIELSERVICE_BROWSER_URL", "http://localhost:8000")
RIJKSPROFIELSERVICE_API_URL = os.environ.get("RIJKSPROFIELSERVICE_API_URL", "http://localhost:8000")
# Bij toegang via host.docker.internal vanuit een container kan de profielservice
# de Host-header afkeuren. Override via env als dat nodig is.
RIJKSPROFIELSERVICE_API_HOST_HEADER = os.environ.get("RIJKSPROFIELSERVICE_API_HOST_HEADER", "")
RIJKSPROFIELSERVICE_CLIENT_ID = os.environ.get("RIJKSPROFIELSERVICE_CLIENT_ID", "wies")
RIJKSPROFIELSERVICE_M2M_CLIENT_ID = os.environ.get("RIJKSPROFIELSERVICE_M2M_CLIENT_ID", "wies-m2m")
RIJKSPROFIELSERVICE_CLIENT_SECRET = os.environ.get("RIJKSPROFIELSERVICE_CLIENT_SECRET", "")
RIJKSPROFIELSERVICE_M2M_CLIENT_SECRET = os.environ.get("RIJKSPROFIELSERVICE_M2M_CLIENT_SECRET", "")
RIJKSPROFIELSERVICE_TOKEN_URL = os.environ.get(
    "RIJKSPROFIELSERVICE_TOKEN_URL",
    "http://localhost:8000/o/token/",
)
RIJKSPROFIELSERVICE_AUTHORIZE_URL = os.environ.get(
    "RIJKSPROFIELSERVICE_AUTHORIZE_URL",
    "http://localhost:8000/o/authorize/",
)
