"""
Django settings for wies project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.utils.translation import gettext_lazy

# env vars
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'local')
WRITABLE_FOLDER = Path(os.environ.get('WRITABLE_FOLDER', ''))  # in deployment these should be explicitly mountable

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "wies"

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

if DJANGO_ENV == 'production' and 'DJANGO_SECRET_KEY' not in os.environ:
    raise EnvironmentError('DJANGO_SECRET_KEY should be set' )
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'mysecret')

# SECURITY WARNING: don't run with debug turned on in production!
if DJANGO_ENV == 'production' and 'DJANGO_DEBUG' == 'true':
    raise EnvironmentError('DJANGO_DEBUG should not be true in production' )
DEBUG = os.environ.get('DJANGO_DEBUG', 'false') == 'true'  # false by default

# TODO: what to do in dev? what in prod?
ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'wies.projects',
    'wies.exact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': WRITABLE_FOLDER / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "nl-nl"
LANGUAGES = [
    ("nl", gettext_lazy("Nederlands")),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "node_modules" / "@nl-rvo",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# TODO: collecstatic should still be added in step. in `just setup`?
# before build such that it lands in image?

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# helpful when understanding internal errors with debug=False
# LOGGING = {
#       'version': 1,
#       'disable_existing_loggers': False,
#       'handlers': {
#           'console': {
#               'class': 'logging.StreamHandler',
#           },
#       },
#       'root': {
#           'handlers': ['console'],
#           'level': 'INFO',
#       },
#       'loggers': {
#           'django': {
#               'handlers': ['console'],
#               'level': 'INFO',
#               'propagate': False,
#           },
#       },
#   }
