# Generated by Django 5.2.4 on 2025-07-21 11:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LEAD', 'LEAD'), ('OPEN', 'OPEN'), ('LOPEND', 'LOPEND'), ('AFGEWEZEN', 'AFGEWEZEN'), ('HISTORISCH', 'HISTORISCH')], default='LEAD', max_length=20)),
                ('organization', models.CharField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL')], default='GROUP', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BE_DEV', 'Backend development'), ('FE_DEV', 'Frontend development'), ('PO', 'Product owner'), ('UX_DES', 'UX designer'), ('AI_CONS', 'AI Consultant'), ('AI_JUR', 'AI Jurist'), ('RES', 'Researcher'), ('DAT_ENG', 'Data engineer'), ('PROJ_LEAD', 'Project leader')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BE_DEV', 'Backend development'), ('FE_DEV', 'Frontend development'), ('PO', 'Product owner'), ('UX_DES', 'UX designer'), ('AI_CONS', 'AI Consultant'), ('AI_JUR', 'AI Jurist'), ('RES', 'Researcher'), ('DAT_ENG', 'Data engineer'), ('PROJ_LEAD', 'Project leader')], max_length=60)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='projects.assignment')),
                ('colleague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='projects.colleague')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.assignment')),
            ],
        ),
    ]
