# Generated by Django 5.2.7 on 2025-10-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'expertises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=98)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(choices=[('otys_iir', 'OTYS IIR')], default='wies', max_length=10)),
                ('source_id', models.CharField(blank=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.brand')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleague', to=settings.AUTH_USER_MODEL)),
                ('expertises', models.ManyToManyField(blank=True, to='projects.expertise')),
                ('skills', models.ManyToManyField(blank=True, to='projects.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LEAD', 'LEAD'), ('VACATURE', 'VACATURE'), ('INGEVULD', 'INGEVULD'), ('AFGEWEZEN', 'AFGEWEZEN')], default='LEAD', max_length=20)),
                ('organization', models.CharField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL')], default='GROUP', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assignments', to='projects.colleague')),
                ('ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.assignment')),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.colleague')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('period_source', models.CharField(choices=[('ASSIGNMENT', 'Neem over van opdracht'), ('SERVICE', 'Specifiek voor dienst')], default='ASSIGNMENT', max_length=10)),
                ('specific_start_date', models.DateField(blank=True, null=True)),
                ('specific_end_date', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.assignment')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='projects.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_source', models.CharField(choices=[('SERVICE', 'Neem over van dienst'), ('PLACEMENT', 'Specifiek voor inzet')], default='SERVICE', max_length=10)),
                ('specific_start_date', models.DateField(blank=True, null=True)),
                ('specific_end_date', models.DateField(blank=True, null=True)),
                ('hours_source', models.CharField(choices=[('SERVICE', 'Neem over van dienst'), ('PLACEMENT', 'Specifiek voor inzet')], default='SERVICE', max_length=10)),
                ('specific_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('colleague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='projects.colleague')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='projects.service')),
            ],
        ),
    ]
